<a href="https://colab.research.google.com/github/nikkijha97/Python/blob/main/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PYTHON (NUMPY)**

# ***Basics***

In [ ]:
# Creating array
import numpy as np


In [ ]:
#0-d array
arr=np.array(42)

In [ ]:
arr


array(42)

In [ ]:
print(arr)
type(arr)

42


numpy.ndarray

In [ ]:
#1-D array
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [ ]:
print(arr1)

[1 2 3]


In [ ]:
#2-D Array
arr2=np.array([[0,1,2],[3,4,5]])
print(arr2)

[[0 1 2]
 [3 4 5]]


In [ ]:
#to know the dimensions
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)


0
1
2


In [ ]:
#to know the shape
arr1.shape

(3,)

# ***Functions for creating Arrays***

**1. Arange**

syntax:np.arange(start,end(exclusive),step)

In [ ]:
a=np.arange(10,100,10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

Linspace

Return evenly spaces no. over specified interval(linespace)

Syntax: np.linspace(start,end(inclusive),step)


In [ ]:
a2=np.linspace(10,66,7)
a2

array([10.        , 19.33333333, 28.66666667, 38.        , 47.33333333,
       56.66666667, 66.        ])

Zeros

syntax: np.zeros(shape)

In [ ]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])