<a href="https://colab.research.google.com/github/nikkijha97/Python/blob/main/numpy%20and%20pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
##creating numpy
## as an array
a=np.array([[1,2,3],[4,5,6]])
print("a",a)
## with arrange
b=np.arange(1,20,3)
print("b",b)
##with linspace
c=np.linspace(1,20,5)
print("c",c)

##with zeroes
d=np.zeros((3,2))
print("d",d)

##with ones

e=np.ones((6,7))
print("e",e)



a [[1 2 3]
 [4 5 6]]
b [ 1  4  7 10 13 16 19]
c [ 1.    5.75 10.5  15.25 20.  ]
d [[0. 0.]
 [0. 0.]
 [0. 0.]]
e [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
## MATRIX ##
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=np.array([[8,9,10]])
print(b)
c=np.concatenate((a,b))
print('c',c)

[[1 2 3]
 [4 5 6]]
[[ 8  9 10]]
c [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [ ]:
##dot product
b=b.transpose()
c=np.dot(a,b)
print(c)

[[ 56]
 [137]]


***PANDAS***

In [ ]:
import pandas as pd

In [ ]:
##creating dataframe
d = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
## Create a DataFrame df from this dictionary data which has the index labels.

df=pd.DataFrame(d, index= labels)
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [ ]:
##converting data frames  to numpy
arr=df.to_numpy()
arr

array([['cat', 2.5, 1, 'yes'],
       ['cat', 3.0, 3, 'yes'],
       ['snake', 0.5, 2, 'no'],
       ['dog', nan, 3, 'yes'],
       ['dog', 5.0, 2, 'no'],
       ['cat', 2.0, 3, 'no'],
       ['snake', 4.5, 1, 'no'],
       ['cat', nan, 1, 'yes'],
       ['dog', 7.0, 2, 'no'],
       ['dog', 3.0, 1, 'no']], dtype=object)

In [ ]:
##converting data frames  to numpy
##converting single or more column to numpy array

arr=df[['age','visits']].to_numpy()
arr

array([[2.5, 1. ],
       [3. , 3. ],
       [0.5, 2. ],
       [nan, 3. ],
       [5. , 2. ],
       [2. , 3. ],
       [4.5, 1. ],
       [nan, 1. ],
       [7. , 2. ],
       [3. , 1. ]])

In [ ]:
##Display a summary of the basic information about this DataFrame and its data (hint: there is a single method that can be called on the DataFrame).

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes


In [ ]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [ ]:
##Return the first 3 rows of the DataFrame df.
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [ ]:
##Return the first 3 rows of the DataFrame df. using
df.iloc[:3]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [ ]:
##Select just the 'animal' and 'age' columns from the DataFrame df.
a=df[['animal','age']]
a

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [ ]:
df.loc[:,[ 'animal','age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [ ]:
df.loc[df.index[[3,4,8]],['animal','age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [ ]:
##Select the data in rows [3, 4, 8] and in columns ['animal', 'age'].
a.iloc[[3,4,8]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [ ]:
df.loc[df.index[[3,4,8]],['animal','age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [ ]:
##Select only the rows where the number of visits is greater than 2.
df[df['visits']>2]

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

In [ ]:
##Select the rows where the age is missing, i.e. it is NaN.
df[df['age'].isnull()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [ ]:
##Select the rows where the animal is a cat and the age is less than 3.
df[(df['animal']=='cat') & (df['age']<3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [ ]:
##Select the rows the age is between 2 and 4 (inclusive).
df[(2<=df['age']) & (df['age']<=4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

In [ ]:
df[df['age'].between(2,4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

In [ ]:
##Change the age in row 'f' to 1.5.
df.loc['f', 'age']=1.5
df


animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [ ]:
##Calculate the sum of all visits in df (i.e. find the total number of visits).
df['visits'].sum()

19

In [ ]:
##Calculate the mean age for each different animal in df.
